spring.application.name=c02-d06-spring-microservices-19-spring-boot-employee-service-actuators

server.port=8090

#Exposes all endpoints under /actuator
#Hit: http://localhost:8080/actuator
management.endpoints.web.exposure.include=*

#To see all /health info
#Hit: http://localhost:8080/actuator/health
management.endpoint.health.show-details=ALWAYS

#To see info about app, add following info in application properties. Then enable info env variable.
#Hit: http://localhost:8080/actuator/info
info.app.name=ActuatorDemo
info.app.version=1.2.3
management.info.env.enabled=true

#If you want to shut down the application, there is an actuator for shut down as well. Everyone can’t shut down. If you are exposing it, you should write it in properties file.
#Hit: http://localhost:8080/actuator/shutdown using POST method
management.endpoint.shutdown.enabled=true

#Customises the actuator end point from /actuator to /appActuator & /health to /appHealth.
#management.endpoints.web.base-path=/appActuator
#management.endpoints.web.path-mapping.health=appHealth










